### ISSUE TITLE
Add input to the post request

### ISSUE THREAD

**Issue by haugstve** [makers-in-oslo/titanic-prod#7]
We need to design an API

**Comment by haugstve** [comment]
What format will the payload have
What do we do with missing data
Should multiple predictions be possible in one POST request?

**Comment by haugstve** [comment]
Should multiple predictions be possible in one POST request?

This is true for Watson Machine Learning. Do we want to check other providers and see if there is a standard?

**Comment by haugstve** [comment]
### Amazon SageMaker model endpoint
(example)[https://aws.amazon.com/blogs/machine-learning/call-an-amazon-sagemaker-model-endpoint-using-amazon-api-gateway-and-aws-lambda/]

**Comment by MMron** [comment]
### Google cloud 
TL;DR: able to score multiple samples, no feature names required 

https://cloud.google.com/ai-platform/prediction/docs/getting-started-scikit-xgboost
#### GCloud
```
[6.8,  2.8,  4.8,  1.4]
[6.0,  3.4,  4.5,  1.6]
```
#### Rest API
```
{
  "instances": [

    [6.8,  2.8,  4.8,  1.4],
    [6.0,  3.4,  4.5,  1.6]

  ] 
```

**Comment by MMron** [comment]
## WML

https://wml-api-pyclient.mybluemix.net/
```
>>> scoring_payload = {'fields': ['GENDER','AGE','MARITAL_STATUS','PROFESSION'], 'values': [['M',23,'Single','Student'],['M',55,'Single','Executive']]}
>>> predictions = client.deployments.score(scoring_url, scoring_payload)
```

**Comment by haugstve** [comment]
### WML 

[docs](https://watson-ml-api.mybluemix.net/?_ga=2.35630817.1360011513.1583830990-683135201.1577803313#!/Deployments/post_v3_wml_instances_instance_id_published_models_published_model_id_deployments_deployment_id_online)

Example
`{
  "fields": [
    "name",
    "age",
    "position",
    "prediction",
    "probability"
  ],
  "labels": [
    "personal",
    "camping"
  ],
  "values": [
    [
      "john",
      33,
      "engineer",
      "personal",
      [
        0.6744664422398081,
        0.32553355776019194
      ]
    ],
    [
      "mike",
      23,
      "student",
      "camping",
      [
        0.2794765664946941,
        0.7205234335053059
      ]
    ]
  ]
}`

**Comment by haugstve** [comment]
{ key:value
  col1: val[row_n, col1],
  col2: val[row_n, col2],
  ...
    col_m: val[row_n, col_m],
}

**Comment by haugstve** [comment]
{
"name": "Dr. d"
"age": 23
"sex": "male"
}
